### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by kimmoda** [zahlio/Gamers-Live#1]

**Comment by zahlio** [comment]
Start by creating the sql database: https://github.com/zahlio/Gamers-Live/blob/master/installer/Database%20Files/Read%20me.txt

Then but the folder 'Gamers Live' live on webserver and go to '/installer' and start the installation.

**Comment by kimmoda** [comment]
what is serial key?

**Comment by DemonRem** [comment]
@zahlio  

still key is needed for this action
